export interface SoftwareTopic {
  name: string;
  body: string;
  topics?: string[];
}

export interface Program {
  slug: string;
  name: string;
  breadcrumb: string;
  heading: string;
  intro: string[];
  softwareNote: { title: string; body: string[] };
  software: SoftwareTopic[];
}

const AUTOCAD_BODY =
  'AutoCAD is a commercial computer-aided design (CAD) and drafting software application. Developed and marketed by Autodesk, AutoCAD was first released in December 1982 as a desktop app running on microcomputers with internal graphics controllers. Before AutoCAD was introduced, most commercial CAD programs ran on mainframe computers or minicomputers, with each CAD operator working at a separate graphics terminal. Since 2010, AutoCAD was released as a mobile- and web app as well, marketed as AutoCAD 360. AutoCAD is used across a wide range of industries, by Architects, Project managers, Engineers, Graphic Designers, City Planners and many other professionals.';

const AUTOCAD_FULL_BODY = `${AUTOCAD_BODY} AutoCAD is licensed, for free, to students, educators, and educational institutions, with a 36-month renewable license available. The student version of AutoCAD is functionally identical to the full commercial version, with one exception: DWG files created or edited by a student version have an internal bit-flag set (the "educational flag"). When such a DWG file is printed by any version of AutoCAD (commercial or student) older than AutoCAD 2014 SP1, the output includes a plot stamp/banner on all four sides. Objects created in the Student Version cannot be used for commercial use.`;

const AUTOCAD_FULL_TOPICS = [
  'Introduction',
  'History',
  'Advantages',
  'Design cycle',
  'GUI of AutoCAD',
  'Co-ordinate system',
  'Absolute co-ordinate system (X,Y)',
  'How to do on screen',
  'Units / Limits / Zoom / Line',
  'Relative rectangle co-ordinate system',
  '@X-displacement, Y-displacement',
  'Polar co-ordinate system — @distance < angle',
  'Functional keys F1 to F12',
  'List of draw commands',
  'Secondary draw commands',
  'Enquiry commands',
  'Display commands',
  'Object snap — endpoint, midpoint, centre, quadrant, perpendicular, intersection, tangent, nearest, apparent intersection, parallel',
  'Selection commands — pick box method, window, crossing window, window polygon, crossing polygon, single, fence, previous, last, add, remove, on, quick select',
  'Modify commands & practicals',
  'Advance modify commands',
  'Measure',
  'Hatch / Hatch edit',
  'Property tool bar / Text / Tables',
  'Layers',
  'Dimensions & dimension style manager',
  'Isometric',
  'Productivity tools',
  'Block / Insert / W-Block / Block edit',
  'Design centre',
  'Tool pallets',
  'Dynamic block creation & saving',
  'Attributes',
  'External references',
  'Viewports',
  'Layout settings & templates',
  'Printing & plot',
];

const CAD_3D: SoftwareTopic = {
  name: '3D CAD (AutoCAD)',
  body: AUTOCAD_BODY,
  topics: [
    '3D modeling concepts in AutoCAD',
    'Understand and use viewpoint and UCS',
    'Wireframe modeling',
    'Solid modeling & editing',
    'Mesh modeling & editing',
    'Surface modeling & editing',
    'Create & manage 2D views from 3D models',
    'Materials, lights & rendering',
    'Working with images',
    'Import and export',
  ],
};

const CAD_2D: SoftwareTopic = {
  name: '2D CAD (AutoCAD)',
  body: AUTOCAD_BODY,
  topics: [
    'Introduction',
    'File management',
    'Orthographic drawings',
    'View management',
    'Display management',
    'Layer management',
    'Selection methods',
    'Parametric drawings',
    'Symbol creation using block',
    'BOM / Joinery details creation',
    'Isometric drawings',
    'Perspective drawings',
    'Annotations and dimensions',
    'Team work',
    'Layout management',
    'Publish and plot',
  ],
};

const AUTOCAD_FULL: SoftwareTopic = {
  name: 'AutoCAD',
  body: AUTOCAD_FULL_BODY,
  topics: AUTOCAD_FULL_TOPICS,
};

export const programs: Program[] = [
  {
    slug: 'civil-cadd',
    name: 'Civil CADD',
    breadcrumb: 'Civil CADD',
    heading: 'Civil CADD Program',
    intro: [
      'Civil Engineering is a professional engineering discipline that deals with the design, construction, and maintenance of the physical and naturally built environment, including public works such as roads, bridges, canals, dams, airports, sewerage systems, pipelines, structural components of buildings, and railways. Civil Engineering takes place in the public sector from municipal through to national governments, and in the private sector from individual homeowners through to international companies.',
      'Civil engineering is the application of physical and scientific principles for solving the problems of society, and its history is intricately linked to advances in the understanding of physics and mathematics throughout history. Because civil engineering is a wide-ranging profession, including several specialized sub-disciplines, its history is linked to knowledge of structures, materials science, geography, geology, soils, hydrology, environment, mechanics and other fields.',
    ],
    softwareNote: {
      title: 'Civil Engineering Software',
      body: [
        'Many software programs are available for each discipline of Civil Engineering. Most civil engineers practice in specialized subsets of civil engineering, such as geotechnical engineering, structural engineering, transportation engineering, hydraulic engineering, environmental engineering, project and construction management and land surveying.',
      ],
    },
    software: [
      {
        name: '3DsMax',
        body: 'Autodesk 3ds Max, formerly 3D Studio and 3D Studio Max, is a professional 3D computer graphics program for making 3D animations, models, games, and images. It is developed and produced by Autodesk Media and Entertainment. It has modeling capabilities and flexible plugin architecture and can be used on the Microsoft Windows platform. It is frequently used by video game developers, many TV commercial studios and architectural visualization studios. It is also used for movie effects and movie pre-visualization. For its modeling and animation tools, the latest version of 3ds Max also features shaders (such as ambient occlusion and subsurface scattering), dynamic simulation, particle systems, radiosity, normal map creation and rendering, global illumination, a customizable user interface, new icons, and its own scripting language. Each chapter begins with concepts and learning objectives, and then moves into an easy way supported by full-colour and real-world exercises. You will create actual animations as you learn a retro-style alarm clock and more while you conquer the techniques of Modeling, Rigging, Animating, Rendering, and Architectural Visualization. When you are finished, you will also have a head start on preparing for the Autodesk 3DS MAX Certified Professional exam.',
        topics: [
          'Introduction to 3ds Max',
          'Modeling using basic primitives',
          'Transforming objects',
          'Customizing working units',
          'Arranging objects using utility tools',
          'Modeling using parametric modifiers',
          'Editing Poly Models using Caddy Interface',
          'Advanced rendering',
          'Spline modeling',
          'Landscaping and modeling using Compound Objects',
          'Construct using Architectural objects',
          'Views - Lights and Cameras',
          'Textures - Basic & Advance',
          'Particle Systems & Forces',
          'Importing other formats',
          'Basics of Animation',
          'Walk-through',
        ],
      },
      CAD_2D,
      CAD_3D,
      AUTOCAD_FULL,
      {
        name: 'E.Tabs',
        body: 'The innovative and revolutionary new ETABS is the ultimate integrated software package for the structural analysis and design of buildings. Incorporating 40 years of continuous research and development, this latest ETABS offers unmatched 3D object based modeling and visualization tools, blazingly fast linear and nonlinear analytical power, sophisticated and comprehensive design capabilities for a wide-range of materials, and insightful graphic displays, reports, and schematic drawings that allow users to quickly and easily decipher and understand analysis and design results. From the start of design conception through the production of schematic drawings, ETABS integrates every aspect of the engineering design process. Creation of models has never been easier - intuitive drawing commands allow for the rapid generation of floor and elevation framing. CAD drawings can be converted directly into ETABS models or used as templates onto which ETABS objects may be overlaid. Design of steel and concrete frames (with automated optimization), composite beams, composite columns, steel joists, and concrete and masonry shear walls is included, as is the capacity check for steel connections and base plates. Models may be realistically rendered, and all results can be shown directly on the structure. Comprehensive and customizable reports are available for all analysis and design output, and schematic construction drawings of framing plans, schedules, details, and cross-sections may be generated for concrete and steel structures. ETABS provides an unequalled suite of tools for structural engineers designing buildings, whether they are working on one-story industrial structures or the tallest commercial high-rises.',
        topics: [
          'Introduction to Structural Engineering',
          'Model generation and editing',
          'Water tank design',
          'Slab design',
          'Staircase design',
          'Shear wall design',
          'Assigning loads and load combinations',
          'Analysis and design results interpretation',
        ],
      },
      {
        name: 'Revit (Architecture)',
        body: "Autodesk Revit is a building information modelling (BIM) software for Architects, Landscape Architects, Structural Engineers, MEP Engineers, Designers and contractors. The software allows users to design a building and structure and its components in 3D, annotate the model with 2D drafting elements, and access building information from the building model's database. Revit is 4D BIM capable with tools to plan and track various stages in the building's lifecycle, from concept to construction and later maintenance and/or demolition. Revit includes categories of objects ('families' in Revit terminology). These fall into three groups: System Families, such as walls, floors, roofs and ceilings, built inside a project; Loadable families/components, which are built with primitives (extrusions, sweeps, etc.) separately from the project and loaded into a project for use; and In-Place Families, which are built in-situ within a project with the same toolset as loadable components. An experienced user can create realistic and accurate families ranging from furniture to lighting fixtures, as well as import existing models from other programs. Revit families can be created as parametric models with dimensions and properties. This lets users modify a given component by changing predefined parameters such as height, width or number in the case of an array.",
        topics: [
          'BIM concepts and project setup',
          'Levels, grids and datum',
          'System families - walls, floors, roofs, ceilings',
          'Loadable families and in-place families',
          'Parametric family creation',
          'Types, instances and instance parameters',
          'Annotation and documentation',
          'Rendering and visualisation',
        ],
      },
      {
        name: 'Revit (MEP)',
        body: 'Autodesk Revit MEP is a single software application that aids a BIM (Building Information Modeling) workflow from theory to construction. It was created by Autodesk for professionals who engage in MEP (Mechanical, Electrical, and Plumbing) Engineering. Autodesk Revit is a parametric building modeler which is able to leverage dynamic information in intelligent models - allowing complex building systems to be precisely designed and verified in less amount of time. It allows users to draw a building, structure and its constituents in 3D, note the model with 2D drafting elements, and access building information from the building model database.',
        topics: [
          'Introduction',
          'Linking Revit files to MEP collaboration',
          'Introduction to plenum levels',
          'Creating plenum levels',
          'Creation of spaces and zones',
          'Heating and cooling calculations',
          'Energy analysis',
          'HVAC ducting',
          'Placing air terminals (supply, return & exhaust)',
          'Placing mechanical equipments',
          'Creating systems',
          'Generating layouts',
          'Creating duct legends',
          'Plumbing & piping',
          'Hydronic type plumbing',
          'Placing plumbing fixtures',
          'Sanitation systems',
          'Fire protection system',
          'Placing sprinklers',
        ],
      },
      {
        name: 'StaadPro',
        body: 'STAAD.Pro is a structural analysis and design software application originally developed by Research Engineers International in 1997. In late 2005, Research Engineers International was bought by Bentley Systems. STAAD.Pro is one of the most widely used structural analysis and design software products worldwide. It supports over 90 international steel, concrete, timber & aluminium design codes. It can make use of various forms of analysis from the traditional static analysis to more recent analysis methods like p-delta analysis, geometric non-linear analysis, Pushover analysis (Static-Non Linear Analysis) or a buckling analysis. It can also make use of various forms of dynamic analysis methods from time history analysis to response spectrum analysis. Additionally, STAAD.Pro is interoperable with applications such as RAM Connection, AutoPIPE, SACS and many more engineering design and analysis applications to further improve collaboration between the different disciplines involved in a project. STAAD can be used for analysis and design of all types of structural projects from plants, buildings, and bridges to towers, tunnels, metro stations, water/wastewater treatment plants and more.',
        topics: [
          'Introduction to Structural Engineering',
          'Introduction to STAAD.Pro V8i',
          'Model generation and editing',
          'Assigning loads',
          'Automatic load generations: slab, wind and moving loads',
          'Creating load combinations',
          'Concrete design',
          'Column and beam design',
          'Seismology, seismic analysis and design',
          'Pushover analysis',
          'Dynamic analysis',
          'Foundation designs',
          'Response spectrum',
          'Isolated, combined, strip, mat and pile cap',
          'Time history analysis',
          'FEM / FEA introduction',
          'Water tank design, slab design, staircase design',
          'Shear wall design',
          'Bridge deck design using STAAD.Beava',
          'Steel design and steel frame structure design',
          'Overhead transmission line towers design',
          'Report generation and plotting',
        ],
      },
      {
        name: 'RCC Detailing',
        body: 'RCC Detailing covers the complete workflow of reinforced concrete detailing with AutoCAD Structural Detailing, from element creation through to automatic drawing preparation and bar bending schedules.',
        topics: [
          'Introduction to RCC Detailing',
          'AutoCAD Structural Detailing',
          'Effective usage of country specific templates and standards',
          'Element creation',
          'Automatic drawing preparation',
          'Manual bar bending schedule',
          'Slab creation with surface distribution',
          'RCC detailing of foundation',
          'Beam',
          'Slab',
          'Staircase',
          'Retaining wall',
          'Concrete pipe',
          'Concrete tank',
          'Print',
        ],
      },
      {
        name: 'SAP 2000',
        body: 'SAP2000 is general-purpose civil-engineering software ideal for the analysis and design of any type of structural system. Created by engineers for effective engineering, SAP2000 is the ideal software tool for users of any experience level, designing any structural system. SAP2000 is a general purpose finite element program which performs the static or dynamic, linear or nonlinear analysis of structural systems. It is also a powerful design tool to design structures following AASHTO specifications, ACI and AISC building codes.',
        topics: [
          'Finite element fundamentals',
          'Static and dynamic analysis',
          'Linear and nonlinear analysis',
          'Design to AASHTO, ACI and AISC codes',
          'Structural system modelling',
          'Results interpretation and reporting',
        ],
      },
      {
        name: 'GstarCAD',
        body: 'GstarCAD is well-known alternative CAD software of high compatibility with ACAD. With 25 years of continuous improvement and lean innovation, today GstarCAD is far ahead in performance, stability and other key indicators and becomes leading CAD software in the world. With new technologies, innovative features and outstanding performance, the DWG-based Collaborative Design of GstarCAD helps improve project design efficiency and significantly reduce error and cost. Advantages of GstarCAD: drawing data incremental storage and transmission; multi-person and multi-direction drawing reference; timely, synchronous and asynchronous drawing data update; smart drawing version management and tracing; easy check of design changes in reference drawings; convenient project import and export.',
        topics: AUTOCAD_FULL_TOPICS,
      },
      {
        name: 'MXROAD',
        body: 'Bentley MXROAD is an advanced, string-based modeling tool that enables the rapid and accurate design of all road types. With MXROAD, you can quickly create design alternatives to build the ideal road system. After a final design alternative is selected, you can automate much of the design detailing process, saving time and money. At its core, MXROAD uses 3D string modeling technology - a powerful yet concise method of creating 3D surfaces. The interoperable database allows engineers to create and annotate 3D project models in the most popular AEC platforms or in Windows.',
        topics: [
          'Design Creativity - dynamic placement and change functionality for 2D and 3D alignments',
          'Intersection Design - string-model based, dynamically re-grade intersections as needed',
          'Superelevation Design - automated approach with standards in a rules file',
          'Pavement Layer Generator and Volumetrics',
          'Design Rules - apply local, company, and project standards',
        ],
      },
      {
        name: 'SketchUp',
        body: 'SketchUp, formerly Google SketchUp, is a 3D modeling computer program for a wide range of drawing applications such as architectural, interior design, landscape architecture, civil and mechanical engineering, film and video game design. SketchUp is owned by Trimble Inc., a mapping, surveying and navigation equipment company. There is an online library of free model assemblies (e.g. windows, doors, automobiles), 3D Warehouse, to which users may contribute models. The program includes drawing layout functionality, allows surface rendering in variable "styles", supports third-party "plug-in" programs hosted on a site called Extension Warehouse to provide other capabilities (e.g. near photo-realistic rendering) and enables placement of its models within Google Earth.',
        topics: [
          'Interface and navigation',
          'Drawing and modification tools',
          'Groups and components',
          '3D Warehouse and Extension Warehouse',
          'Materials and styles',
          'Layout and documentation',
          'Rendering and walkthroughs',
        ],
      },
    ],
  },
  {
    slug: 'mechanical-cadd',
    name: 'Mechanical CADD',
    breadcrumb: 'Mechanical CADD',
    heading: 'Mechanical CADD Program',
    intro: [
      'Mechanical engineering is the discipline that applies engineering, physics, engineering mathematics, and materials science principles to design, analyze, manufacture, and maintain mechanical systems. It is one of the oldest and broadest of the engineering disciplines.',
      'The mechanical engineering field requires an understanding of core areas including mechanics, dynamics, thermodynamics, materials science, structural analysis, and electricity. In addition to these core principles, mechanical engineers use tools such as computer-aided design (CAD), computer-aided manufacturing (CAM), and product life cycle management to design and analyze manufacturing plants, industrial equipment and machinery, heating and cooling systems, transport systems, aircraft, watercraft, robotics, medical devices, weapons, and others. It is the branch of engineering that involves the design, production, and operation of machinery.',
    ],
    softwareNote: {
      title: 'Mechanical Engineering Software',
      body: [
        'Many mechanical engineering companies, especially those in industrialized nations, have begun to incorporate computer-aided engineering (CAE) programs into their existing design and analysis processes, including 2D and 3D solid modeling computer-aided design (CAD). This method has many benefits, including easier and more exhaustive visualization of products, the ability to create virtual assemblies of parts, and the ease of use in designing mating interfaces and tolerances.',
        'Other CAE programs commonly used by mechanical engineers include product lifecycle management (PLM) tools and analysis tools used to perform complex simulations. Analysis tools may be used to predict product response to expected loads, including fatigue life and manufacturability. These tools include finite element analysis (FEA), computational fluid dynamics (CFD), and computer-aided manufacturing (CAM).',
      ],
    },
    software: [
      {
        name: 'ANSYS',
        body: 'ANSYS Mechanical is a finite element analysis tool for structural analysis, including linear, nonlinear and dynamic studies. The software creates simulated computer models of structures, electronics, or machine components to simulate strength, toughness, elasticity, temperature distribution, electromagnetism, fluid flow, and other attributes. Ansys is used to determine how a product will function with different specifications, without building test products or conducting crash tests. For example, Ansys software may simulate how a bridge will hold up after years of traffic, how to best process salmon in a cannery to reduce waste, or how to design a slide that uses less material without sacrificing safety. Most Ansys simulations are performed using the Ansys Workbench software. Typically Ansys users break down larger structures into small components that are each modeled and tested individually. A user may start by defining the dimensions of an object, and then adding weight, pressure, temperature and other physical properties. Finally, the Ansys software simulates and analyzes movement, fatigue, fractures, fluid flow, temperature distribution, electromagnetic efficiency, and other effects over time.',
      },
      CAD_2D,
      CAD_3D,
      AUTOCAD_FULL,
      {
        name: 'ANSYS APDL',
        body: 'Mechanical APDL has also graphics but does not require it for execution. One can do CAD modeling (very cumbersome) and FEM modeling all inside the same screen. Since everything is pretty much done via commands (kind of on the fly scripting) it is much more convenient to make loops and repeat actions, such as running hundreds of load cases and automating parametric studies.',
      },
      {
        name: 'AnsysWorkbench',
        body: 'Ansys Workbench (Mechanical) is more graphics focused and geometry focused. There is less direct connection to the FEM. Workbench provides easy to learn, easy to use environment. APDL scripts are still possible to use but it is a bit cumbersome.',
        topics: [
          'Introduction to CAE',
          'General procedure involved in FEA',
          'GUI of ANSYS Workbench',
          'Working on a project',
          'CAD modeling using ANSYS Workbench',
          'Defining and assigning materials',
          'Generating the mesh',
          'Optimizing the model to refine mesh',
          'Working with different boundary conditions',
          'Surface and line models',
          'Static structural analysis',
          'Modal analysis',
          'Buckling analysis',
          'Thermal analysis',
          'Coupled field (thermal stress)',
          'Post processing',
        ],
      },
      {
        name: 'CATIA',
        body: 'CATIA is a multi-platform software suite for computer-aided design, computer-aided manufacturing and computer-aided engineering, widely used across the automotive, aerospace and industrial equipment sectors for surface and solid design, assembly and drafting.',
        topics: [
          'CATIA user interface',
          'Creating and editing sketches',
          'Creating sketch based features',
          'Creating transformation features',
          'Creating dress up features',
          'Creating advanced replication tools',
          'Editing parts in assembly',
          'Creating surface features',
          'Generative sheetmetal design',
          'Drawing view generation',
          'Bill of materials, balloons',
          'Finalizing the drawing and printing',
          'Dress up on 2D views',
          'Real time rendering',
          'GD&T',
        ],
      },
      {
        name: 'SolidWorks',
        body: 'SolidWorks is a solid modeling computer-aided design and computer-aided engineering application used for part modeling, assembly design, sheet metal, weldments and detailing, with an integrated simulation and product data management workflow.',
        topics: [
          'Sketcher basics',
          '3D sketching',
          'Part modeling',
          'Creating reference geometries',
          'Editing features',
          'Advanced modeling tools',
          'Configuration',
          'Design table / library features',
          'Import/export of files',
          'Surface overview',
          'Bottom-up assembly',
          'Top-down assembly',
          'Exploding assemblies',
          'Simulation / Detailing',
          'BOM, balloon tools',
          'Sheet metal',
          'PDM Works',
          'Weldment',
          'GD&T',
        ],
      },
      {
        name: 'Hypermesh',
        body: 'Hypermesh training course enables participants to work on Hypermesh 12.0 software, a computer aided engineering (CAE) simulations software platform. The training enables the trainees to create finite element models for analysis and prepare high-quality meshes in an efficient manner. This program offers the skills needed to work with geometry editing tools for preparing CAD models for the meshing process. During the Hypermesh training, the attendees will have knowledge about the BatchMeshing technique that facilitates users to mesh several files in the background to match the standards set by users. By the end of the training, the participants will inculcate skills on Finite Element Analysis (FEA); Shell, Tetra, and HyperMeshing; creating hexa and penta mesh; assemblies - welding and swapping parts; topography and topology; thermal, static and normal mode analysis; preparing models for analysis and geometry for meshing; defining manufacturing constraints; 2D and 3D shape optimization; 1D and 2D size optimization; and results visualization with HyperMesh.',
        topics: [
          'Introduction to Hypermesh, create nodes, temp nodes, delete',
          'Create lines, line edit',
          'Distances, length, circle',
          'Create surfaces, surface edit',
          'Quick edit, point edit, edge edit',
          'Exercises - 2D surface creation',
          'Mid surface',
          'Defeature',
          'Create solid, solid edit',
          'Planes, cones, spheres, torus, ruled, spline, skin, spin',
          'Drag, line drag, element offset, auto mesh',
          'Edit element, smooth',
          'Split, replace, detach, order change',
          'Quality index',
          'Solid map',
          'Linear solids, solid mesh',
          'Tetra mesh',
          'Split 3D elements, edit elements',
          'Introduction to 1D',
          'Beams, rod, springs',
          'Rigid, line mesh',
          'Final project',
        ],
      },
      {
        name: 'Inventor',
        body: 'Inventor software takes manufacturers beyond 3D to Digital Prototyping by giving engineers a comprehensive and flexible set of tools for 3D mechanical design, simulation, tooling, visualization and documentation. With Inventor software, engineers can integrate 2D AutoCAD drawings and 3D data into a single digital model, creating a virtual representation of the final product that enables them to validate the form, fit, and function of the product before it is ever built. Digital Prototyping with Inventor software enables you to design, visualize, and simulate products digitally, helping you to build better products, reduce development costs, and get to market faster. This software incorporates integrated motion simulation and assembly stress analysis, whereby users are given options to input driving loads, dynamic components, friction loads and further run the dynamic simulation to test how the product will function in a real-world scenario. Autodesk Inventor finite element analysis feature allows users to validate the component design through testing part performance under loads.',
      },
      {
        name: 'NX',
        body: 'NX was formerly known as "Unigraphics". NX is an advanced high-end CAD/CAM/CAE, which has been owned since 2007 by Siemens PLM Software. It is used, among other tasks, for design (parametric and direct solid/surface modeling); engineering analysis (static; dynamic; electromagnetic; thermal, using the finite element method; and fluid, using the finite volume method); and manufacturing finished design by using included machining modules. NX is a direct competitor to CATIA, Creo, Autodesk Inventor, and SolidWorks.',
      },
      {
        name: 'Pro-E / CREO',
        body: 'Creo is a family or suite of Computer-aided design (CAD) apps supporting product design for discrete manufacturers and is developed by PTC. The suite consists of apps, each delivering a distinct set of capabilities for a user role within product development. Creo runs on Microsoft Windows and provides apps for 3D CAD parametric feature solid modeling, 3D direct modeling, 2D orthographic views, Finite Element Analysis and simulation, schematic design, technical illustrations, and viewing and visualization. Creo Elements/Pro and Creo Parametric compete directly with CATIA, Siemens NX/Solidedge, and SolidWorks. The Creo suite of apps replaces and supersedes PTC products formerly known as Pro/ENGINEER, CoCreate, and ProductView. Creo is part of a broader product development system developed by PTC. It connects to PTC other solutions that aid product development, including Windchill for Product Lifecycle Management (PLM), Mathcad for engineering calculations and Arbortext for enterprise publishing software.',
        topics: [
          'Creo/Parametric concepts',
          'Using the Creo/Parametric interface',
          'Creating sketcher geometry',
          'Relations and parameters',
          'Creating extrudes, revolves, and ribs',
          'Measuring and inspecting models',
          'Advanced reference management',
          'Layers, family tables & UDF',
          'Creating cross-sections, display styles, and combined views',
          'Substituting components by rep, envelope, and model',
          'Creating and using assemblies',
        ],
      },
    ],
  },
  {
    slug: 'project-management',
    name: 'Project Management',
    breadcrumb: 'Project Management',
    heading: 'Project Management Program',
    intro: [
      'Project Planning is part of project management, which relates to the use of schedules such as Gantt charts to plan and subsequently report progress within the project environment. Initially, the project scope is defined and the appropriate methods for completing the project are determined. Following this step, the duration for the various tasks necessary to complete the work is listed and grouped into a work breakdown structure.',
      'The logical dependencies between tasks are defined using an activity network diagram that enables identification of the critical path. Float or slack time in the schedule can be calculated using project management software. Then the necessary resources can be estimated and costs for each activity can be allocated to each resource, giving the total project cost. At this stage, the project plan may be optimized to achieve the appropriate balance between resource usage and project duration to comply with the project objectives. Once established and agreed, the plan becomes what is known as the baseline. Progress will be measured against the baseline throughout the life of the project. Analyzing progress compared to the baseline is known as earned value management.',
    ],
    softwareNote: {
      title: 'Project Management Software',
      body: [
        'Our Project Management program trains participants on the two most widely deployed planning platforms in the industry - Oracle Primavera P6 and Microsoft Project - covering scheduling, resource management, cost control, tracking and reporting end to end.',
      ],
    },
    software: [
      {
        name: 'Primavera',
        body: "Oracle's Primavera P6 Enterprise Project Portfolio Management is the most powerful, robust, and easy-to-use solution for globally prioritizing, planning, managing, and executing projects, programs, and portfolios. Primavera P6 Enterprise Project Portfolio Management is an integrated project portfolio management (PPM) solution comprising role-specific functionality to satisfy each team member's needs, responsibilities, and skills. It provides a single solution for managing projects of any size, adapts to various levels of complexities within a project, and intelligently scales to meet the needs of various roles, functions, or skill levels in your organization and on your project team.",
        topics: [
          'Data structure of Primavera',
          'Calendars',
          'Work breakdown structure',
          'Activities / Relationship / Constraints',
          'Scheduling',
          'Activity, Resource and Project Codes',
          'Create and assign Roles and Resources',
          'Resource analysis and levelling',
          'Baseline',
          'Update and track project progress',
          'User defined fields, global change, views',
          'Check in / Check out',
          'Generate reports',
        ],
      },
      {
        name: 'MSP (Microsoft Project)',
        body: "Core Microsoft Project (MSP, MSOP or Win Proj) is a project management software program, developed and sold by Microsoft, which is designed to assist a project manager in developing a plan, assigning resources to tasks, tracking progress, managing the budget, and analyzing workloads. MS Project was the company's third Microsoft Windows-based application, and within a couple of years of its introduction it became the dominant PC-based project management software. Although branded as a member of the Microsoft Office family, it never has been included in any of the Office suites (like Visio). It is available currently in two editions, Standard and Professional. MS Project's proprietary file format is .mpp. Microsoft Project and Microsoft Project Server are the cornerstones of the Microsoft Office Enterprise Project Management (EPM) product.",
        topics: [
          'Calendar',
          'Task / Relationships',
          'Work breakdown structure',
          'Constraints and recurring task',
          'Define and assign resource',
          'Resource analysis and leveling',
          'Baseline',
          'Update project progress',
          'Tracking',
          'Earned value analysis',
          'Customization and formatting',
          'Generate reports',
        ],
      },
    ],
  },
  {
    slug: 'electrical-cadd',
    name: 'Electrical CADD',
    breadcrumb: 'Electrical Engineering',
    heading: 'Electrical Engineering Program',
    intro: [
      'Electrical engineering is a field of engineering that generally deals with the study and application of electricity, electronics, and electromagnetism. This field first became an identifiable occupation in the latter half of the nineteenth century after commercialization of the electric telegraph, the telephone, and electric power distribution and use. It now covers a wide range of subfields including electronics, digital computers, power engineering, telecommunications, control systems, RF engineering, and signal processing.',
      'Electrical engineering may include electronic engineering. Where a distinction is made, usually outside of the United States, electrical engineering is considered to deal with the problems associated with systems such as electric power transmission and electrical machines, whereas electronic engineering deals with the study of electronic systems including computers, communication systems, integrated circuits, and radar. From a different point-of-view, electrical engineers are usually concerned with using electricity to transmit electric power, while electronic engineers are concerned with using electricity to process information. The subdisciplines can overlap, for example, in the growth of power electronics, and the study of the behavior of large electrical grids under the control of digital computers and electronics.',
    ],
    softwareNote: {
      title: 'Electrical Engineering Software',
      body: [
        'The Electrical CADD program focuses on drafting discipline and the AutoCAD platform as applied to electrical schematics, panel layouts and control system documentation.',
      ],
    },
    software: [
      {
        name: 'Drafting',
        body: 'Drafting or technical drawing is the means by which mechanical engineers design products and create instructions for manufacturing parts. A technical drawing can be a computer model or hand-drawn schematic showing all the dimensions necessary to manufacture a part, as well as assembly notes, a list of required materials, and other pertinent information. A U.S. mechanical engineer or skilled worker who creates technical drawings may be referred to as a drafter or draftsman. Drafting has historically been a two-dimensional process, but computer-aided design (CAD) programs now allow the designer to create in three dimensions.',
      },
      {
        name: 'PPM Concept',
        body: "AutoCAD is a software application for COMPUTER AIDED DRAFTING (CAD) and drafting. The software supports both 2D and 3D formats. The software is developed and sold by Autodesk, Inc., first released in December 1982 by Autodesk in the year following the purchase of the first form of the software by Autodesk founder, John Walker. AutoCAD is Autodesk's flagship product and by March 1986 had become the most ubiquitous microcomputer design program in the world, utilizing functions such as \"polylines\" and \"curve fitting\". Prior to the introduction of AutoCAD, most other CAD programs ran on mainframe computers or minicomputers, with each CAD operator (user) working at a graphical terminal or workstation.",
      },
      AUTOCAD_FULL,
    ],
  },
  {
    slug: 'architecture-cadd',
    name: 'Architecture CADD',
    breadcrumb: 'Architecture and Interior',
    heading: 'Architecture and Interior Program',
    intro: [
      'INTERIOR DESIGN is the art and science of enhancing the interiors, sometimes including the exterior, of a space or building, to achieve a healthier and more aesthetically pleasing environment for the end user. An interior designer is someone who plans, researches, coordinates and manage such projects. Interior design is a multifaceted profession that includes conceptual development, space planning, site inspections, programming, research, communicating with the stakeholders of a project, construction management, and execution of the design.',
      'Interior design is the process of shaping the experience of interior space, through the manipulation of spatial volume as well as surface treatment for the betterment of human functionality.',
    ],
    softwareNote: {
      title: 'Architecture and Interior Software',
      body: [
        'The Architecture and Interior program brings together drafting, BIM modelling and visualisation so that a designer can take a space from concept sketch to photo-real presentation and construction documentation.',
      ],
    },
    software: [
      CAD_2D,
      CAD_3D,
      {
        name: 'Revit (Architecture)',
        body: "Autodesk Revit is a building information modelling (BIM) software for Architects, Landscape Architects, Structural Engineers, MEP Engineers, Designers and contractors. The software allows users to design a building and structure and its components in 3D, annotate the model with 2D drafting elements, and access building information from the building model's database. Revit is 4D BIM capable with tools to plan and track various stages in the building's lifecycle, from concept to construction and later maintenance and/or demolition.",
        topics: [
          'BIM concepts and project setup',
          'System families - walls, floors, roofs, ceilings',
          'Loadable and in-place families',
          'Parametric family creation',
          'Schedules and documentation',
          'Rendering and visualisation',
        ],
      },
      {
        name: '3DsMax',
        body: 'Autodesk 3ds Max is a professional 3D computer graphics program for making 3D animations, models, games, and images, widely used by architectural visualization studios for interior and exterior walkthroughs, lighting studies and photo-real stills.',
        topics: [
          'Modeling using basic primitives and parametric modifiers',
          'Architectural objects and landscaping',
          'Views - Lights and Cameras',
          'Textures - basic & advance',
          'Advanced rendering',
          'Basics of animation and walk-through',
        ],
      },
      {
        name: 'SketchUp',
        body: 'SketchUp, formerly Google SketchUp, is a 3D modeling computer program for a wide range of drawing applications such as architectural, interior design, landscape architecture, civil and mechanical engineering, film and video game design. There is an online library of free model assemblies, 3D Warehouse, to which users may contribute models.',
        topics: [
          'Interface and navigation',
          'Drawing and modification tools',
          'Groups and components',
          '3D Warehouse',
          'Materials and styles',
          'Layout and documentation',
        ],
      },
    ],
  },
];

export const computerCourses = ['Basic Computers', 'JAVA', 'C++', 'Web Designing'];

export function getProgram(slug: string) {
  return programs.find((p) => p.slug === slug);
}
